version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: crypto_signals_timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_DB: crypto_signals
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crypto_signals_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - timescaledb

volumes:
  timescaledb_data:
  pgadmin_data: